### ISSUE TITLE
%20 in file path

### ISSUE THREAD

**Issue by GongT** [ikatyang/linguist-languages#278]
generated `index.mjs` looks like:
```js
import _0 from "../data/1C%20Enterprise.mjs"
import _1 from "../data/2-Dimensional%20Array.mjs"
import _2 from "../data/4D.mjs"
import _3 from "../data/ABAP.mjs"
import _4 from "../data/ABAP%20CDS.mjs"
```

nodejs do not allow urlEncoded strings. (best not using any space in filename)

**Comment by ikatyang** [comment]
The space is coming from the name provided by the linguist repository, which I think it'd be better to preserve it for consistency. The percent-encoded URLs are actually suggested by the [Node.js ESM document](https://nodejs.org/docs/latest-v18.x/api/esm.html#urls), and Node.js does not work without it as far as I can tell. Can you share more info as of why it does not work for you? e.g., the Node.js version and steps to reproduce the issue.

**Comment by GongT** [comment]
Oh, I never do escape before, it works like i want. I will check my toolchain, it seems some tool do not support escaped file url.

thank you for your reply!

**Comment by f0rr0** [comment]
This does not work in bun

**Comment by f0rr0** [comment]
this does not work with bun
